=== Nailalvz/PRO/eclipse-workspace/XMLExamples/XMLSchemaAvanzados/Ejercicio5_videoclub.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="facturas">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="factura" minOccurs="0"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="factura">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="datos_cliente" minOccurs="1"
					maxOccurs="1" />
				<xsd:element ref="datos_factura" minOccurs="1"
					maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="datos_cliente">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nombre" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="apellido" minOccurs="2" maxOccurs="2" />
				<xsd:element ref="dni" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="telefono" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="ident" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="nombre" type="xsd:string" />

	<xsd:element name="apellido" type="xsd:string" />

	<xsd:element name="dni">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[0-9]{8}[A-Z]" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>

	<xsd:element name="telefono">
		<xsd:simpleType>
			<xsd:restriction base="xsd:positiveInteger"/>
		</xsd:simpleType>
	</xsd:element>

	<xsd:element name="datos_factura">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="resguardo" minOccurs="1" maxOccurs="1" />
					<xsd:element ref="alquileres" minOccurs="0" maxOccurs="1" />
					<xsd:element ref="compras" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="resguardo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="forma_pago" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="importe_total" minOccurs="1"
					maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="forma_pago" type="xsd:string" />

	<xsd:element name="importe_total" type="xsd:positiveInteger" />

	<xsd:element name="alquileres">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="fecha" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="peliculas" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="fecha" type="xsd:date" />

	<xsd:element name="peliculas">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="pelicula" minOccurs="1"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="pelicula">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titulo" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="genero" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="duracion" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="actores" minOccurs="1" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id_pelicula" type="xsd:string" use="required" />
			<xsd:attribute name="valoracion" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="titulo" type="xsd:string" />

	<xsd:element name="genero" type="xsd:string" />

	<xsd:element name="duracion" type="xsd:positiveInteger" />

	<xsd:element name="actores">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="actor" minOccurs="3" maxOccurs="3" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="actor">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nombre" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="apellido" minOccurs="1" maxOccurs="2" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="compras">
		<xsd:complexType>
			<xsd:choice>
				<xsd:element ref="dvds" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="cintas" minOccurs="1" maxOccurs="1" />
				<xsd:element name="dvds_cintas">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element ref="dvds" minOccurs="1" maxOccurs="1" />
							<xsd:element ref="cintas" minOccurs="1" maxOccurs="1" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="dvds">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="dvd" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="dvd">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titulo" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="fecha" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="extras" minOccurs="1"
					maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="extras" type="xsd:string" />



	<xsd:element name="cintas">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="cinta" minOccurs="1"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="cinta">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="titulo" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="formato" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="rebobinado" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="formato" type="xsd:string" />

	<xsd:element name="rebobinado">
		<xsd:complexType />
	</xsd:element>
</xsd:schema>

=== Nailalvz/PRO/eclipse-workspace/XMLExamples/XMLSchemaAvanzados/Ejercicio5_Videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>

<facturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="ejercicio5_videoclub.xsd">
       <factura>
            <datos_cliente ident="A1">
                <nombre>Lucia</nombre>
                <apellido>Álvarez</apellido>
                <apellido>Pérez</apellido>
                <dni>34567824H</dni>
                <telefono>666666666</telefono>
            </datos_cliente>
            <datos_factura>
                <resguardo>
                    <forma_pago>
                        Tarjeta
                    </forma_pago>
                    <importe_total>
                       55
                    </importe_total>
                </resguardo>
                <alquileres>
                    <fecha>2022-02-03</fecha>
                    <peliculas>
                        <pelicula id_pelicula="AB" valoracion="Excelente">
                            <titulo>El resplandor</titulo>
                            <genero>Terror</genero>
                            <duracion>146</duracion>
                            <actores>
                                <actor>
                                    <nombre>Jack</nombre>
                                    <apellido>Nicholson</apellido>
                                </actor>
                                <actor>
                                    <nombre>Shelley</nombre>
                                    <apellido>Duvall</apellido>
                                </actor>
                                <actor>
                                    <nombre>Danny</nombre>
                                    <apellido>Lloyd</apellido>
                                </actor>
                            </actores>
                        </pelicula>
                    </peliculas>
                </alquileres>
            </datos_factura>
       </factura>
       
              <factura>
            <datos_cliente ident="A2">
                <nombre>Álvaro</nombre>
                <apellido>García</apellido>
                <apellido>Pérez</apellido>
                <dni>89765432P</dni>
                <telefono>666665436</telefono>
            </datos_cliente>
            <datos_factura>
                <resguardo>
                    <forma_pago>
                        Efectivo
                    </forma_pago>
                    <importe_total>
                       80
                    </importe_total>
                </resguardo>
                
                <alquileres>
                    <fecha>2022-02-04</fecha>
                    <peliculas>
                        <pelicula id_pelicula="CD" valoracion="buena">
                            <titulo>Inception</titulo>
                            <genero>Ciencia Ficción</genero>
                            <duracion>148</duracion>
                            <actores>
                                <actor>
                                    <nombre>Leonardo</nombre>
                                    <apellido>Dicaprio</apellido>
                                </actor>
                                <actor>
                                    <nombre>Ken</nombre>
                                    <apellido>Watanabe</apellido>
                                </actor>
                                <actor>
                                    <nombre>Joseph</nombre>
                                    <apellido>Gordon-Levitt</apellido>
                                </actor>
                            </actores>
                        </pelicula>
                    </peliculas>
                </alquileres>
                
                <compras>
                <dvds>
	                <dvd>
	                	<titulo>2001</titulo>
	                	<fecha>1968-04-02</fecha>
	                	<extras>Si</extras>
	                </dvd>
                </dvds>
                </compras>
            </datos_factura>
       </factura>
       
       
</facturas>
